name: Selenium Test

on: [push, pull_request]

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # O la versión que uses

      - name: Instalar dependencias
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install selenium pytest

      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Ejecutar tests
        run: |
          source venv/bin/activate
          pytest
